development:
  adapter: postgresql
  database: <%= ENV['APP_DEVELOPMENT_DATABASE'] %>
  pool: 15
  timeout:
  encoding: unicode
  username: postgres
  password:  <%= ENV['APP_DB_PASSWORD'] %>
  host: localhost


test:
  adapter: postgresql
  database: <%= ENV['APP_TEST_DATABASE'] %>
  pool: 15
  timeout:
  encoding: unicode
  username: postgres
  password:  <%= ENV['APP_DB_PASSWORD'] %>
  host: localhost


production:
  adapter: postgresql
  database: <%= ENV['APP_PRODUCTION_DATABASE'] %>
  pool: 15
  timeout:
  encoding: unicode
  username: postgres
  password:  <%= ENV['APP_DB_PASSWORD'] %>
  host: localhost



