# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
production:
  adapter: postgresql
  database: dbname_production
  pool: 5
  timeout: 
  username: dbusername
  password: dbpassword
  host: localhost
  port: 5432

