#!/usr/bin/env ruby
 

require 'rubygems'
require "bundler/setup"
require 'daemons'
#require 'action_view'
require "#{ENV['GB_RAILS_ROOT']}/config/environment"


options = {
    :log_output => true,
  }

Daemons.run_proc('script/mailman_server', options) do
  
end

