#!/usr/bin/env ruby



ENV['GB_RAILS_ROOT']='/Users/joe/development/products/grpbldr/env/dev/grpbldr'
 

 

require 'rubygems'
require "bundler/setup"
require 'daemons'
require 'action_view'
require "#{ENV['GB_RAILS_ROOT']}/config/environment"


options = {
    :log_output => true,
  }

Daemons.run('script/mailman_server', options)

