require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AgendaLineItemsController do

  # This should return the minimal set of attributes required to create a valid
  # AgendaLineItem. As you add validations to AgendaLineItem, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AgendaLineItemsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all agenda_line_items as @agenda_line_items" do
      agenda_line_item = AgendaLineItem.create! valid_attributes
      get :index, {}, valid_session
      assigns(:agenda_line_items).should eq([agenda_line_item])
    end
  end

  describe "GET show" do
    it "assigns the requested agenda_line_item as @agenda_line_item" do
      agenda_line_item = AgendaLineItem.create! valid_attributes
      get :show, {:id => agenda_line_item.to_param}, valid_session
      assigns(:agenda_line_item).should eq(agenda_line_item)
    end
  end

  describe "GET new" do
    it "assigns a new agenda_line_item as @agenda_line_item" do
      get :new, {}, valid_session
      assigns(:agenda_line_item).should be_a_new(AgendaLineItem)
    end
  end

  describe "GET edit" do
    it "assigns the requested agenda_line_item as @agenda_line_item" do
      agenda_line_item = AgendaLineItem.create! valid_attributes
      get :edit, {:id => agenda_line_item.to_param}, valid_session
      assigns(:agenda_line_item).should eq(agenda_line_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AgendaLineItem" do
        expect {
          post :create, {:agenda_line_item => valid_attributes}, valid_session
        }.to change(AgendaLineItem, :count).by(1)
      end

      it "assigns a newly created agenda_line_item as @agenda_line_item" do
        post :create, {:agenda_line_item => valid_attributes}, valid_session
        assigns(:agenda_line_item).should be_a(AgendaLineItem)
        assigns(:agenda_line_item).should be_persisted
      end

      it "redirects to the created agenda_line_item" do
        post :create, {:agenda_line_item => valid_attributes}, valid_session
        response.should redirect_to(AgendaLineItem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved agenda_line_item as @agenda_line_item" do
        # Trigger the behavior that occurs when invalid params are submitted
        AgendaLineItem.any_instance.stub(:save).and_return(false)
        post :create, {:agenda_line_item => {}}, valid_session
        assigns(:agenda_line_item).should be_a_new(AgendaLineItem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AgendaLineItem.any_instance.stub(:save).and_return(false)
        post :create, {:agenda_line_item => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested agenda_line_item" do
        agenda_line_item = AgendaLineItem.create! valid_attributes
        # Assuming there are no other agenda_line_items in the database, this
        # specifies that the AgendaLineItem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AgendaLineItem.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => agenda_line_item.to_param, :agenda_line_item => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested agenda_line_item as @agenda_line_item" do
        agenda_line_item = AgendaLineItem.create! valid_attributes
        put :update, {:id => agenda_line_item.to_param, :agenda_line_item => valid_attributes}, valid_session
        assigns(:agenda_line_item).should eq(agenda_line_item)
      end

      it "redirects to the agenda_line_item" do
        agenda_line_item = AgendaLineItem.create! valid_attributes
        put :update, {:id => agenda_line_item.to_param, :agenda_line_item => valid_attributes}, valid_session
        response.should redirect_to(agenda_line_item)
      end
    end

    describe "with invalid params" do
      it "assigns the agenda_line_item as @agenda_line_item" do
        agenda_line_item = AgendaLineItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AgendaLineItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => agenda_line_item.to_param, :agenda_line_item => {}}, valid_session
        assigns(:agenda_line_item).should eq(agenda_line_item)
      end

      it "re-renders the 'edit' template" do
        agenda_line_item = AgendaLineItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AgendaLineItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => agenda_line_item.to_param, :agenda_line_item => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested agenda_line_item" do
      agenda_line_item = AgendaLineItem.create! valid_attributes
      expect {
        delete :destroy, {:id => agenda_line_item.to_param}, valid_session
      }.to change(AgendaLineItem, :count).by(-1)
    end

    it "redirects to the agenda_line_items list" do
      agenda_line_item = AgendaLineItem.create! valid_attributes
      delete :destroy, {:id => agenda_line_item.to_param}, valid_session
      response.should redirect_to(agenda_line_items_url)
    end
  end

end
