require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ContestSignupsController do

  # This should return the minimal set of attributes required to create a valid
  # ContestSignup. As you add validations to ContestSignup, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ContestSignupsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all contest_signups as @contest_signups" do
      contest_signup = ContestSignup.create! valid_attributes
      get :index, {}, valid_session
      assigns(:contest_signups).should eq([contest_signup])
    end
  end

  describe "GET show" do
    it "assigns the requested contest_signup as @contest_signup" do
      contest_signup = ContestSignup.create! valid_attributes
      get :show, {:id => contest_signup.to_param}, valid_session
      assigns(:contest_signup).should eq(contest_signup)
    end
  end

  describe "GET new" do
    it "assigns a new contest_signup as @contest_signup" do
      get :new, {}, valid_session
      assigns(:contest_signup).should be_a_new(ContestSignup)
    end
  end

  describe "GET edit" do
    it "assigns the requested contest_signup as @contest_signup" do
      contest_signup = ContestSignup.create! valid_attributes
      get :edit, {:id => contest_signup.to_param}, valid_session
      assigns(:contest_signup).should eq(contest_signup)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ContestSignup" do
        expect {
          post :create, {:contest_signup => valid_attributes}, valid_session
        }.to change(ContestSignup, :count).by(1)
      end

      it "assigns a newly created contest_signup as @contest_signup" do
        post :create, {:contest_signup => valid_attributes}, valid_session
        assigns(:contest_signup).should be_a(ContestSignup)
        assigns(:contest_signup).should be_persisted
      end

      it "redirects to the created contest_signup" do
        post :create, {:contest_signup => valid_attributes}, valid_session
        response.should redirect_to(ContestSignup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved contest_signup as @contest_signup" do
        # Trigger the behavior that occurs when invalid params are submitted
        ContestSignup.any_instance.stub(:save).and_return(false)
        post :create, {:contest_signup => {}}, valid_session
        assigns(:contest_signup).should be_a_new(ContestSignup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ContestSignup.any_instance.stub(:save).and_return(false)
        post :create, {:contest_signup => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested contest_signup" do
        contest_signup = ContestSignup.create! valid_attributes
        # Assuming there are no other contest_signups in the database, this
        # specifies that the ContestSignup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ContestSignup.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => contest_signup.to_param, :contest_signup => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested contest_signup as @contest_signup" do
        contest_signup = ContestSignup.create! valid_attributes
        put :update, {:id => contest_signup.to_param, :contest_signup => valid_attributes}, valid_session
        assigns(:contest_signup).should eq(contest_signup)
      end

      it "redirects to the contest_signup" do
        contest_signup = ContestSignup.create! valid_attributes
        put :update, {:id => contest_signup.to_param, :contest_signup => valid_attributes}, valid_session
        response.should redirect_to(contest_signup)
      end
    end

    describe "with invalid params" do
      it "assigns the contest_signup as @contest_signup" do
        contest_signup = ContestSignup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ContestSignup.any_instance.stub(:save).and_return(false)
        put :update, {:id => contest_signup.to_param, :contest_signup => {}}, valid_session
        assigns(:contest_signup).should eq(contest_signup)
      end

      it "re-renders the 'edit' template" do
        contest_signup = ContestSignup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ContestSignup.any_instance.stub(:save).and_return(false)
        put :update, {:id => contest_signup.to_param, :contest_signup => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested contest_signup" do
      contest_signup = ContestSignup.create! valid_attributes
      expect {
        delete :destroy, {:id => contest_signup.to_param}, valid_session
      }.to change(ContestSignup, :count).by(-1)
    end

    it "redirects to the contest_signups list" do
      contest_signup = ContestSignup.create! valid_attributes
      delete :destroy, {:id => contest_signup.to_param}, valid_session
      response.should redirect_to(contest_signups_url)
    end
  end

end
