require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MemberNotificationPreferencesController do

  # This should return the minimal set of attributes required to create a valid
  # MemberNotificationPreference. As you add validations to MemberNotificationPreference, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MemberNotificationPreferencesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all member_notification_preferences as @member_notification_preferences" do
      member_notification_preference = MemberNotificationPreference.create! valid_attributes
      get :index, {}, valid_session
      assigns(:member_notification_preferences).should eq([member_notification_preference])
    end
  end

  describe "GET show" do
    it "assigns the requested member_notification_preference as @member_notification_preference" do
      member_notification_preference = MemberNotificationPreference.create! valid_attributes
      get :show, {:id => member_notification_preference.to_param}, valid_session
      assigns(:member_notification_preference).should eq(member_notification_preference)
    end
  end

  describe "GET new" do
    it "assigns a new member_notification_preference as @member_notification_preference" do
      get :new, {}, valid_session
      assigns(:member_notification_preference).should be_a_new(MemberNotificationPreference)
    end
  end

  describe "GET edit" do
    it "assigns the requested member_notification_preference as @member_notification_preference" do
      member_notification_preference = MemberNotificationPreference.create! valid_attributes
      get :edit, {:id => member_notification_preference.to_param}, valid_session
      assigns(:member_notification_preference).should eq(member_notification_preference)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MemberNotificationPreference" do
        expect {
          post :create, {:member_notification_preference => valid_attributes}, valid_session
        }.to change(MemberNotificationPreference, :count).by(1)
      end

      it "assigns a newly created member_notification_preference as @member_notification_preference" do
        post :create, {:member_notification_preference => valid_attributes}, valid_session
        assigns(:member_notification_preference).should be_a(MemberNotificationPreference)
        assigns(:member_notification_preference).should be_persisted
      end

      it "redirects to the created member_notification_preference" do
        post :create, {:member_notification_preference => valid_attributes}, valid_session
        response.should redirect_to(MemberNotificationPreference.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved member_notification_preference as @member_notification_preference" do
        # Trigger the behavior that occurs when invalid params are submitted
        MemberNotificationPreference.any_instance.stub(:save).and_return(false)
        post :create, {:member_notification_preference => {}}, valid_session
        assigns(:member_notification_preference).should be_a_new(MemberNotificationPreference)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MemberNotificationPreference.any_instance.stub(:save).and_return(false)
        post :create, {:member_notification_preference => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested member_notification_preference" do
        member_notification_preference = MemberNotificationPreference.create! valid_attributes
        # Assuming there are no other member_notification_preferences in the database, this
        # specifies that the MemberNotificationPreference created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MemberNotificationPreference.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => member_notification_preference.to_param, :member_notification_preference => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested member_notification_preference as @member_notification_preference" do
        member_notification_preference = MemberNotificationPreference.create! valid_attributes
        put :update, {:id => member_notification_preference.to_param, :member_notification_preference => valid_attributes}, valid_session
        assigns(:member_notification_preference).should eq(member_notification_preference)
      end

      it "redirects to the member_notification_preference" do
        member_notification_preference = MemberNotificationPreference.create! valid_attributes
        put :update, {:id => member_notification_preference.to_param, :member_notification_preference => valid_attributes}, valid_session
        response.should redirect_to(member_notification_preference)
      end
    end

    describe "with invalid params" do
      it "assigns the member_notification_preference as @member_notification_preference" do
        member_notification_preference = MemberNotificationPreference.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MemberNotificationPreference.any_instance.stub(:save).and_return(false)
        put :update, {:id => member_notification_preference.to_param, :member_notification_preference => {}}, valid_session
        assigns(:member_notification_preference).should eq(member_notification_preference)
      end

      it "re-renders the 'edit' template" do
        member_notification_preference = MemberNotificationPreference.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MemberNotificationPreference.any_instance.stub(:save).and_return(false)
        put :update, {:id => member_notification_preference.to_param, :member_notification_preference => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested member_notification_preference" do
      member_notification_preference = MemberNotificationPreference.create! valid_attributes
      expect {
        delete :destroy, {:id => member_notification_preference.to_param}, valid_session
      }.to change(MemberNotificationPreference, :count).by(-1)
    end

    it "redirects to the member_notification_preferences list" do
      member_notification_preference = MemberNotificationPreference.create! valid_attributes
      delete :destroy, {:id => member_notification_preference.to_param}, valid_session
      response.should redirect_to(member_notification_preferences_url)
    end
  end

end
