require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NotificationTypesController do

  # This should return the minimal set of attributes required to create a valid
  # NotificationType. As you add validations to NotificationType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NotificationTypesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all notification_types as @notification_types" do
      notification_type = NotificationType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:notification_types).should eq([notification_type])
    end
  end

  describe "GET show" do
    it "assigns the requested notification_type as @notification_type" do
      notification_type = NotificationType.create! valid_attributes
      get :show, {:id => notification_type.to_param}, valid_session
      assigns(:notification_type).should eq(notification_type)
    end
  end

  describe "GET new" do
    it "assigns a new notification_type as @notification_type" do
      get :new, {}, valid_session
      assigns(:notification_type).should be_a_new(NotificationType)
    end
  end

  describe "GET edit" do
    it "assigns the requested notification_type as @notification_type" do
      notification_type = NotificationType.create! valid_attributes
      get :edit, {:id => notification_type.to_param}, valid_session
      assigns(:notification_type).should eq(notification_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NotificationType" do
        expect {
          post :create, {:notification_type => valid_attributes}, valid_session
        }.to change(NotificationType, :count).by(1)
      end

      it "assigns a newly created notification_type as @notification_type" do
        post :create, {:notification_type => valid_attributes}, valid_session
        assigns(:notification_type).should be_a(NotificationType)
        assigns(:notification_type).should be_persisted
      end

      it "redirects to the created notification_type" do
        post :create, {:notification_type => valid_attributes}, valid_session
        response.should redirect_to(NotificationType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved notification_type as @notification_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        NotificationType.any_instance.stub(:save).and_return(false)
        post :create, {:notification_type => {}}, valid_session
        assigns(:notification_type).should be_a_new(NotificationType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NotificationType.any_instance.stub(:save).and_return(false)
        post :create, {:notification_type => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested notification_type" do
        notification_type = NotificationType.create! valid_attributes
        # Assuming there are no other notification_types in the database, this
        # specifies that the NotificationType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        NotificationType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => notification_type.to_param, :notification_type => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested notification_type as @notification_type" do
        notification_type = NotificationType.create! valid_attributes
        put :update, {:id => notification_type.to_param, :notification_type => valid_attributes}, valid_session
        assigns(:notification_type).should eq(notification_type)
      end

      it "redirects to the notification_type" do
        notification_type = NotificationType.create! valid_attributes
        put :update, {:id => notification_type.to_param, :notification_type => valid_attributes}, valid_session
        response.should redirect_to(notification_type)
      end
    end

    describe "with invalid params" do
      it "assigns the notification_type as @notification_type" do
        notification_type = NotificationType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NotificationType.any_instance.stub(:save).and_return(false)
        put :update, {:id => notification_type.to_param, :notification_type => {}}, valid_session
        assigns(:notification_type).should eq(notification_type)
      end

      it "re-renders the 'edit' template" do
        notification_type = NotificationType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NotificationType.any_instance.stub(:save).and_return(false)
        put :update, {:id => notification_type.to_param, :notification_type => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested notification_type" do
      notification_type = NotificationType.create! valid_attributes
      expect {
        delete :destroy, {:id => notification_type.to_param}, valid_session
      }.to change(NotificationType, :count).by(-1)
    end

    it "redirects to the notification_types list" do
      notification_type = NotificationType.create! valid_attributes
      delete :destroy, {:id => notification_type.to_param}, valid_session
      response.should redirect_to(notification_types_url)
    end
  end

end
