require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SysConfigurationsController do

  # This should return the minimal set of attributes required to create a valid
  # SysConfiguration. As you add validations to SysConfiguration, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SysConfigurationsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all sys_configurations as @sys_configurations" do
      sys_configuration = SysConfiguration.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sys_configurations).should eq([sys_configuration])
    end
  end

  describe "GET show" do
    it "assigns the requested sys_configuration as @sys_configuration" do
      sys_configuration = SysConfiguration.create! valid_attributes
      get :show, {:id => sys_configuration.to_param}, valid_session
      assigns(:sys_configuration).should eq(sys_configuration)
    end
  end

  describe "GET new" do
    it "assigns a new sys_configuration as @sys_configuration" do
      get :new, {}, valid_session
      assigns(:sys_configuration).should be_a_new(SysConfiguration)
    end
  end

  describe "GET edit" do
    it "assigns the requested sys_configuration as @sys_configuration" do
      sys_configuration = SysConfiguration.create! valid_attributes
      get :edit, {:id => sys_configuration.to_param}, valid_session
      assigns(:sys_configuration).should eq(sys_configuration)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SysConfiguration" do
        expect {
          post :create, {:sys_configuration => valid_attributes}, valid_session
        }.to change(SysConfiguration, :count).by(1)
      end

      it "assigns a newly created sys_configuration as @sys_configuration" do
        post :create, {:sys_configuration => valid_attributes}, valid_session
        assigns(:sys_configuration).should be_a(SysConfiguration)
        assigns(:sys_configuration).should be_persisted
      end

      it "redirects to the created sys_configuration" do
        post :create, {:sys_configuration => valid_attributes}, valid_session
        response.should redirect_to(SysConfiguration.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sys_configuration as @sys_configuration" do
        # Trigger the behavior that occurs when invalid params are submitted
        SysConfiguration.any_instance.stub(:save).and_return(false)
        post :create, {:sys_configuration => {}}, valid_session
        assigns(:sys_configuration).should be_a_new(SysConfiguration)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SysConfiguration.any_instance.stub(:save).and_return(false)
        post :create, {:sys_configuration => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sys_configuration" do
        sys_configuration = SysConfiguration.create! valid_attributes
        # Assuming there are no other sys_configurations in the database, this
        # specifies that the SysConfiguration created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SysConfiguration.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => sys_configuration.to_param, :sys_configuration => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested sys_configuration as @sys_configuration" do
        sys_configuration = SysConfiguration.create! valid_attributes
        put :update, {:id => sys_configuration.to_param, :sys_configuration => valid_attributes}, valid_session
        assigns(:sys_configuration).should eq(sys_configuration)
      end

      it "redirects to the sys_configuration" do
        sys_configuration = SysConfiguration.create! valid_attributes
        put :update, {:id => sys_configuration.to_param, :sys_configuration => valid_attributes}, valid_session
        response.should redirect_to(sys_configuration)
      end
    end

    describe "with invalid params" do
      it "assigns the sys_configuration as @sys_configuration" do
        sys_configuration = SysConfiguration.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SysConfiguration.any_instance.stub(:save).and_return(false)
        put :update, {:id => sys_configuration.to_param, :sys_configuration => {}}, valid_session
        assigns(:sys_configuration).should eq(sys_configuration)
      end

      it "re-renders the 'edit' template" do
        sys_configuration = SysConfiguration.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SysConfiguration.any_instance.stub(:save).and_return(false)
        put :update, {:id => sys_configuration.to_param, :sys_configuration => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sys_configuration" do
      sys_configuration = SysConfiguration.create! valid_attributes
      expect {
        delete :destroy, {:id => sys_configuration.to_param}, valid_session
      }.to change(SysConfiguration, :count).by(-1)
    end

    it "redirects to the sys_configurations list" do
      sys_configuration = SysConfiguration.create! valid_attributes
      delete :destroy, {:id => sys_configuration.to_param}, valid_session
      response.should redirect_to(sys_configurations_url)
    end
  end

end
